name: Simple Blog
#url: http://example.org
#description: A stylish blog using the Solarized color palette

#permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

markdown: redcarpet
redcarpet:
 extensions: ["fenced_code_blocks", "tables"]
